// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['service']['App']['Greet'](arg1);
}

export function GreetExplainNginx(arg1) {
  return window['go']['service']['App']['GreetExplainNginx'](arg1);
}

export function GreetExplainRdb(arg1) {
  return window['go']['service']['App']['GreetExplainRdb'](arg1);
}

export function GreetExplainSlow(arg1) {
  return window['go']['service']['App']['GreetExplainSlow'](arg1);
}

export function GreetLogin(arg1) {
  return window['go']['service']['App']['GreetLogin'](arg1);
}

export function GreetSqlExec(arg1) {
  return window['go']['service']['App']['GreetSqlExec'](arg1);
}

export function GreetSqlQuery(arg1) {
  return window['go']['service']['App']['GreetSqlQuery'](arg1);
}

export function SelectFile(arg1, arg2) {
  return window['go']['service']['App']['SelectFile'](arg1, arg2);
}
