// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function GreetExplainNginx(arg1:string):Promise<string>;

export function GreetExplainRdb(arg1:string):Promise<string>;

export function GreetExplainSlow(arg1:string):Promise<string>;

export function GreetLogin(arg1:string):Promise<string>;

export function GreetSqlExec(arg1:string):Promise<string>;

export function GreetSqlQuery(arg1:string):Promise<string>;

export function SelectFile(arg1:string,arg2:string):Promise<string>;
